Repository pknu-wap/2022_WAP-APP-TEAM1, pull requests merged in 2022-04, with the labels that each got.

#1 프로젝트 초기 설정
  .gitignore
  README.md
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/wap/storemanagement/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/wap/storemanagement/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: documentation

#7 메인 액티비티 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wap/storemanagement/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: chore, presentation layer

#11 메인화면 - 일정 레이아웃 작성
  app/build.gradle
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/MyScheduleView.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/TextAlign.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  build.gradle
Labels: presentation layer

#12 hilt 설정 & base 클래스 상속
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wap/storemanagement/App.kt
  app/src/main/java/com/wap/storemanagement/MainActivity.kt
  app/src/main/java/com/wap/storemanagement/di/module/DispatcherModule.kt
  app/src/main/java/com/wap/storemanagement/di/provider/DispatcherProviderImpl.kt
  build.gradle
Labels: presentation layer, di

#14 메인화면 - 일정에 없는 직원 목록 레이아웃 작성
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/OffMemberView.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: presentation layer

#18 메인화면 - fragment_home.xml 작성
  app/src/main/java/com/wap/storemanagement/FragmentHome.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/MyScheduleView.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/OffMemberView.kt
  app/src/main/res/layout/calendar_view.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
Labels: presentation layer

#20 일정 더미데이터 생성
  app/src/main/java/com/wap/storemanagement/data/entity/ScheduleEntity.kt
Labels: data layer

#22 일정 Viewmodel 구현
  app/build.gradle
  app/src/main/java/com/wap/storemanagement/FragmentHome.kt
  app/src/main/java/com/wap/storemanagement/data/entity/ScheduleEntity.kt
  app/src/main/java/com/wap/storemanagement/fake/FakeFactory.kt
  app/src/main/java/com/wap/storemanagement/ui/home/HomeFragment.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/MyScheduleView.kt
  build.gradle
Labels: domain layer, presentation layer
