Repository pknu-wap/2022_WAP-APP-TEAM1, pull requests merged in 2022-05, with the labels that each got.

#26 Entitiy, Interface 코드적용
  app/src/main/java/com/wap/storemanagement/MainActivity.kt
  app/src/main/java/com/wap/storemanagement/data/entity/Schedule.kt
  app/src/main/java/com/wap/storemanagement/data/entity/ScheduleEntity.kt
  app/src/main/java/com/wap/storemanagement/data/entity/ToDo.kt
  app/src/main/java/com/wap/storemanagement/data/entity/User.kt
  app/src/main/java/com/wap/storemanagement/data/local/ScheduleLocalDataSource.kt
  app/src/main/java/com/wap/storemanagement/fake/FakeFactory.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: data layer

#33 Data module 생성
  app/build.gradle
  app/src/main/java/com/wap/storemanagement/fake/FakeFactory.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/MyScheduleView.kt
  build.gradle
  data/.gitignore
  data/build.gradle
  data/consumer-rules.pro
  data/proguard-rules.pro
  data/src/androidTest/java/com/wap/data/ExampleInstrumentedTest.kt
  data/src/main/AndroidManifest.xml
  data/src/main/java/com/wap/data/db/Converters.kt
  data/src/main/java/com/wap/data/entity/ScheduleEntity.kt
  data/src/main/java/com/wap/data/entity/UserEntity.kt
  data/src/main/java/com/wap/data/local/ScheduleLocalDataSourceImpl.kt
  data/src/test/java/com/wap/data/ExampleUnitTest.kt
  domain/.gitignore
  domain/build.gradle
  domain/src/main/java/com/wap/domain/entity/Schedule.kt
  domain/src/main/java/com/wap/domain/entity/ToDo.kt
  domain/src/main/java/com/wap/domain/entity/User.kt
  domain/src/main/java/com/wap/domain/local/ScheduleLocalDataSource.kt
  settings.gradle
Labels: data layer, domain layer

#37 Schedule, User Dao 생성
  data/src/main/java/com/wap/data/db/dao/ScheduleDao.kt
  data/src/main/java/com/wap/data/db/dao/UserDao.kt
Labels: data layer

#36 ktlint 설정
  .github/workflows/ktlint-check.yml
  build.gradle
Labels: CI/CD

#39 AppDatabase 추가
  data/src/main/java/com/wap/data/db/AppDatabase.kt
Labels: data layer

#42 SchedulDao startTime 자료형 변경
  data/src/main/java/com/wap/data/db/dao/ScheduleDao.kt
Labels: data layer

#43 ktlint 오류 수정
  .github/workflows/ktlint-check.yml
Labels: bug, CI/CD

#45 ScheduleEntity, UserDao 문제로 인한 build문제 해결
  data/src/main/java/com/wap/data/db/dao/UserDao.kt
  data/src/main/java/com/wap/data/entity/ScheduleEntity.kt
Labels: data layer

#46 ktlint yml 설정
  .github/workflows/reviewdog.yml
Labels: bug

#51 일정 추가 / 수정 화면 레이아웃
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wap/storemanagement/fake/FakeFactory.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/MyScheduleView.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/AddEditScheduleActivity.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/AddEditScheduleTopAppBar.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/CheckDateView.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/SaveButton.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/ScheduleView.kt
  app/src/main/res/layout/activity_schedule.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: presentation layer

#58 ktlint 룰 커스텀
  .editorconfig
Labels: chore, CI/CD

#57 schedule db 구현
  data/build.gradle
  data/src/main/java/com/wap/data/Mapper.kt
  data/src/main/java/com/wap/data/di/module/DatabaseModule.kt
  data/src/main/java/com/wap/data/local/ScheduleLocalDataSourceImpl.kt
  data/src/main/java/com/wap/data/util/Converters.kt
  domain/src/main/java/com/wap/domain/local/ScheduleLocalDataSource.kt
Labels: data layer, domain layer, di

#60 자동 리뷰어 지정
  .github/CODEOWNERS
Labels: CI/CD

#65 Home Compose View - Refactoring
  app/src/main/java/com/wap/storemanagement/ui/basecomposeview/Profile.kt
  app/src/main/java/com/wap/storemanagement/ui/basecomposeview/Schedule.kt
  app/src/main/java/com/wap/storemanagement/ui/basecomposeview/Text.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/MyScheduleView.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/OffMemberView.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/TextAlign.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
Labels: presentation layer

#69 clickable 사용 시 오류 수정
  app/build.gradle
  build.gradle
Labels: bug

#67 Schedule 뷰모델과 DB 연동, test 코드 작성
  app/src/main/java/com/wap/storemanagement/di/module/DataSourceModule.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/utils/MapperExtensions.kt
  data/src/androidTest/java/com/wap/data/ExampleInstrumentedTest.kt
  data/src/androidTest/java/com/wap/data/db/dao/ScheduleDaoTest.kt
  data/src/main/java/com/wap/data/local/ScheduleLocalDataSourceImpl.kt
  domain/src/main/java/com/wap/domain/local/ScheduleLocalDataSource.kt
Labels: bug, data layer, domain layer, presentation layer, di, test

#70 HomeFragment - AddEditScheduleActivity 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wap/storemanagement/di/module/DataSourceModule.kt
  app/src/main/java/com/wap/storemanagement/di/module/RepositoryModule.kt
  app/src/main/java/com/wap/storemanagement/ui/home/HomeFragment.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/MyScheduleView.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/AddEditScheduleActivity.kt
  data/src/main/java/com/wap/data/di/module/DataSourceModule.kt
  data/src/main/java/com/wap/data/local/ScheduleLocalDataSourceImpl.kt
  data/src/main/java/com/wap/data/repository/ScheduleRepository.kt
  domain/src/main/java/com/wap/domain/datasource/ScheduleDataSource.kt
Labels: data layer, domain layer, presentation layer

#73 AddScheduleCard 클릭
  app/src/main/java/com/wap/storemanagement/ui/basecomposeview/Schedule.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/AddEditScheduleActivity.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/ScheduleView.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/TimePicker.kt
  app/src/main/java/com/wap/storemanagement/ui/set/SetScheduleCalendarActivity.kt
  app/src/main/java/com/wap/storemanagement/ui/set/composeview/FixedSchedule.kt
  app/src/main/res/layout/activity_schedule.xml
Labels: presentation layer

#56 todo 레이아웃 /#30
  app/src/main/res/drawable/ic_baseline_add.xml
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/layout/fragment_todo.xml
  app/src/main/res/layout/fragment_todo_item.xml
  app/src/main/res/values/strings.xml
Labels: presentation layer

#76 테스트에서 발생하는 외래키 에러 해결
  data/src/androidTest/java/com/wap/data/db/dao/ScheduleDaoTest.kt
Labels: bug, test

#77 TimePicker Toggle - Composable 추가
  app/src/main/java/com/wap/storemanagement/ui/schedule/AddEditScheduleActivity.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/TimePicker.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/TimePickerToggle.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/TimePickerToggleState.kt
Labels: presentation layer

#78 Add Schedule 버튼 클릭 -> 일정 추가
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/AddEditScheduleActivity.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/Button.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/InputTime.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/TimePicker.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/TimePickerToggle.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/TimePickerToggleState.kt
  app/src/main/res/values/strings.xml
Labels: presentation layer

#81 화면전환
  app/build.gradle
  app/src/main/java/com/wap/storemanagement/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle
Labels: bug, presentation layer

#88 ScheduleId 중복으로 발생하는 AddSchedule 문제 해결
  app/src/main/java/com/wap/storemanagement/MainActivity.kt
  app/src/main/java/com/wap/storemanagement/ui/basecomposeview/Schedule.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/ui/home/composeview/MyScheduleView.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/ScheduleView.kt
Labels: presentation layer

#89 일정 저장 기능 추가
  app/src/main/java/com/wap/storemanagement/fake/FakeFactory.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/AddEditScheduleActivity.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/SaveButton.kt
  data/src/androidTest/java/com/wap/data/db/dao/ScheduleDaoTest.kt
  data/src/main/java/com/wap/data/db/dao/ScheduleDao.kt
  data/src/main/java/com/wap/data/local/ScheduleLocalDataSourceImpl.kt
  data/src/main/java/com/wap/data/repository/ScheduleRepository.kt
  domain/src/main/java/com/wap/domain/datasource/ScheduleDataSource.kt
Labels: data layer, presentation layer

#91 급여화면 구성
  app/src/main/java/com/wap/storemanagement/ui/salary/SalaryFragment.kt
  app/src/main/java/com/wap/storemanagement/ui/salary/composeview/SalaryTopBox.kt
  app/src/main/java/com/wap/storemanagement/ui/salary/composeview/WhiteText.kt
  app/src/main/res/drawable/bg_salary_blue_edge.xml
  app/src/main/res/layout/fragment_salary.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: presentation layer

#95 user data source
  data/src/androidTest/java/com/wap/data/db/dao/UserDaoTest.kt
  data/src/main/java/com/wap/data/Mapper.kt
  data/src/main/java/com/wap/data/di/module/DataSourceModule.kt
  data/src/main/java/com/wap/data/local/UserLocalDataSource.kt
  domain/src/main/java/com/wap/domain/datasource/UserDataSource.kt
Labels: data layer, domain layer, test

#85 할 일 DB
  data/src/main/java/com/wap/data/db/TodoDatabase.kt
  data/src/main/java/com/wap/data/db/dao/TodoDao.kt
  data/src/main/java/com/wap/data/entity/TodoEntity.kt
Labels: data layer, help wanted

#99 일정 수정 기능 추가
  app/src/main/java/com/wap/storemanagement/ui/basecomposeview/Schedule.kt
  app/src/main/java/com/wap/storemanagement/ui/home/ScheduleViewModel.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/AddEditScheduleActivity.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/TimePickerState.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/ScheduleView.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/Button.kt
  app/src/main/java/com/wap/storemanagement/ui/schedule/composeview/timepicker/TimePicker.kt
  app/src/main/java/com/wap/storemanagement/ui/set/composeview/FixedSchedule.kt
Labels: presentation layer

#101 할일 리스트 기능 구현
  app/src/main/java/com/wap/storemanagement/di/module/RepositoryModule.kt
  app/src/main/java/com/wap/storemanagement/ui/todo/ToDoFragment.kt
  app/src/main/java/com/wap/storemanagement/ui/todo/ToDoViewModel.kt
  app/src/main/res/layout/fragment_todo.xml
  app/src/main/res/layout/item_todo.xml
  data/src/androidTest/java/com/wap/data/db/dao/ScheduleDaoTest.kt
  data/src/androidTest/java/com/wap/data/db/dao/UserDaoTest.kt
  data/src/main/java/com/wap/data/Mapper.kt
  data/src/main/java/com/wap/data/db/AppDatabase.kt
  data/src/main/java/com/wap/data/db/TodoDatabase.kt
  data/src/main/java/com/wap/data/db/dao/TodoDao.kt
  data/src/main/java/com/wap/data/di/module/DataSourceModule.kt
  data/src/main/java/com/wap/data/di/module/DatabaseModule.kt
  data/src/main/java/com/wap/data/local/ToDoLocalDataSource.kt
  domain/build.gradle
  domain/src/main/java/com/wap/domain/datasource/ToDoDataSource.kt
  domain/src/main/java/com/wap/domain/entity/ToDo.kt
Labels: bug, data layer, domain layer, presentation layer, di
